# Generated by Django 4.0 on 2022-11-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcourse',
            fields=[
                ('course_id', models.CharField(default='default', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tcourseevent',
            fields=[
                ('course_event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_event_datetime', models.DateTimeField(blank=True, null=True)),
                ('course_event_preptime', models.IntegerField(blank=True, null=True)),
                ('course_event_weightage', models.IntegerField(blank=True, null=True)),
                ('course_event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('course_event_repeat', models.IntegerField(blank=True, null=True)),
                ('course_event_weekday', models.CharField(blank=True, max_length=50, null=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Tpersonalevent',
            fields=[
                ('personal_event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('personal_event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('personal_event_datetime', models.DateTimeField(blank=True, null=True)),
                ('personal_event_duration', models.IntegerField(blank=True, null=True)),
                ('personal_event_preptime', models.IntegerField(blank=True, null=True)),
                ('personal_event_traveltime', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tschedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_generation_reason', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tstudent',
            fields=[
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', unique=True)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_email', models.CharField(blank=True, max_length=200, null=True)),
                ('student_max_studytime', models.IntegerField(blank=True, null=True)),
                ('student_time_pref', models.IntegerField(blank=True, null=True)),
                ('student_max_timeblock', models.IntegerField(blank=True, null=True)),
                ('student_day_starttime', models.IntegerField(blank=True, null=True)),
                ('student_day_endtime', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ttimeslot',
            fields=[
                ('timeslot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timeslot_name', models.CharField(blank=True, max_length=200, null=True)),
                ('timeslot_datetime', models.DateTimeField(blank=True, null=True)),
                ('timeslot_duration', models.IntegerField(blank=True, null=True)),
                ('timeslot_type', models.IntegerField(blank=True, null=True)),
                ('course_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tcourseevent')),
                ('personal_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tpersonalevent')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Tstudentcourse',
            fields=[
                ('student_course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=6, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tcourseclass',
            fields=[
                ('course_class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_class_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_class_weekday', models.CharField(blank=True, max_length=50, null=True)),
                ('course_class_duration', models.IntegerField(blank=True, null=True)),
                ('course_class_time', models.IntegerField(blank=True, null=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
