# Generated by Django 4.0 on 2022-11-19 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'base_note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tcourse',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tCourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tcourseevent',
            fields=[
                ('course_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_event_datetime', models.DateTimeField(blank=True, null=True)),
                ('course_event_duration', models.IntegerField(blank=True, null=True)),
                ('course_event_preptime', models.IntegerField(blank=True, null=True)),
                ('course_event_traveltime', models.IntegerField(blank=True, null=True)),
                ('course_event_weightage', models.IntegerField(blank=True, null=True)),
                ('course_event_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tCourseEvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tpersonalevent',
            fields=[
                ('personal_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('personal_event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('personal_event_datetime', models.DateTimeField(blank=True, null=True)),
                ('personal_event_duration', models.IntegerField(blank=True, null=True)),
                ('personal_event_preptime', models.IntegerField(blank=True, null=True)),
                ('personal_event_traveltime', models.IntegerField(blank=True, null=True)),
                ('timeslot_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tPersonalEvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tschedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_generation_reason', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tSchedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tstudent',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_email', models.CharField(blank=True, max_length=200, null=True)),
                ('student_max_studytime', models.IntegerField(blank=True, null=True)),
                ('student_time_pref', models.IntegerField(blank=True, null=True)),
                ('student_max_timeblock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tStudent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tstudentcourse',
            fields=[
                ('student_course_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tStudentCourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ttimeslot',
            fields=[
                ('timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeslot_name', models.CharField(blank=True, max_length=200, null=True)),
                ('timeslot_datetime', models.DateTimeField(blank=True, null=True)),
                ('timeslot_duration', models.IntegerField(blank=True, null=True)),
                ('timeslot_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tTimeslot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
