# Generated by Django 4.0 on 2022-11-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcourse',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tcourseevent',
            fields=[
                ('course_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_event_datetime', models.DateTimeField(blank=True, null=True)),
                ('course_event_duration', models.IntegerField(blank=True, null=True)),
                ('course_event_preptime', models.IntegerField(blank=True, null=True)),
                ('course_event_traveltime', models.IntegerField(blank=True, null=True)),
                ('course_event_weightage', models.IntegerField(blank=True, null=True)),
                ('course_event_type', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Tpersonalevent',
            fields=[
                ('personal_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('personal_event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('personal_event_datetime', models.DateTimeField(blank=True, null=True)),
                ('personal_event_duration', models.IntegerField(blank=True, null=True)),
                ('personal_event_preptime', models.IntegerField(blank=True, null=True)),
                ('personal_event_traveltime', models.IntegerField(blank=True, null=True)),
                ('timeslot_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tschedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_generation_reason', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tstudent',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_email', models.CharField(blank=True, max_length=200, null=True)),
                ('student_max_studytime', models.IntegerField(blank=True, null=True)),
                ('student_time_pref', models.IntegerField(blank=True, null=True)),
                ('student_max_timeblock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ttimeslot',
            fields=[
                ('timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeslot_name', models.CharField(blank=True, max_length=200, null=True)),
                ('timeslot_datetime', models.DateTimeField(blank=True, null=True)),
                ('timeslot_duration', models.IntegerField(blank=True, null=True)),
                ('timeslot_type', models.IntegerField(blank=True, null=True)),
                ('course_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tcourseevent')),
                ('personal_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tpersonalevent')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Tstudentcourse',
            fields=[
                ('student_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tcourse')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tstudent')),
            ],
        ),
        migrations.AddField(
            model_name='tschedule',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tstudent'),
        ),
        migrations.AddField(
            model_name='tpersonalevent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tstudent'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
