# Generated by Django 4.0 on 2022-12-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tstudentcourse',
            name='course_lec',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tstudentcourse',
            name='course_tut',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
