# Generated by Django 4.0 on 2022-11-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0002_remove_tstudent_user_alter_tpersonalevent_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tstudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', unique=True),
        ),
    ]
