# Generated by Django 4.0 on 2022-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_course_event_traveltime_tcourseevent_course_event_repeat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcourse',
            name='course_name',
        ),
        migrations.AlterField(
            model_name='tcourse',
            name='course_id',
            field=models.CharField(default='default', max_length=20, primary_key=True, serialize=False),
        ),
    ]
