# Generated by Django 4.0 on 2022-11-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_tcourse_course_name_alter_tcourse_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcourseclass',
            name='course_class_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
