# Generated by Django 4.0 on 2022-11-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_tstudent_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tstudentcourse',
            name='course',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
