# Generated by Django 4.0 on 2022-11-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0004_tcourseclass_course_class_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpersonalevent',
            name='timeslot_id',
        ),
        migrations.AddField(
            model_name='tstudent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
