# Generated by Django 4.0 on 2022-11-24 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_tcourseevent_course_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcourseevent',
            name='course_event_duration',
        ),
    ]
